version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongodb
    environment:
      MONGO_DSN: mongodb://ruber:123@mongodb:27017/rubcube_db

  mongodb:
      image: mongo:latest
      ports:
        - 27017:27017
      volumes:
        - ./data:/data/db
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: 123
        MONGO_INITDB_DATABASE: rubcube_db
      volumes:
        - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro


networks:
  default:
    driver: bridge

