import { Injectable } from '@nestjs/common';
import { LogRepo } from '../database/log.repo';

@Injectable()
export class StatisticsService {
  constructor(readonly logModel: LogRepo) {}

  async getStatisticsByGames(games: string[] = []): Promise<any> {
    const filterByGameName = games.length > 0;
    return this.logModel.model.aggregate([
      {
        $match: {
          eventType: 'Kill',
          ...(filterByGameName && {
            gameNameAutoGenerated: { $in: games },
          }),
        },
      },
      {
        $group: {
          _id: {
            gameNameAutoGenerated: '$gameNameAutoGenerated',
            killModType: '$killModType',
          },
          lineNum: { $first: '$logLineNum' },
          countKills: { $sum: 1 },
          countKillsByWorld: {
            $sum: {
              $cond: {
                if: { $eq: ['$killerName', '<world>'] },
                then: 1,
                else: 0,
              },
            },
          },
        },
      },
      {
        $group: {
          _id: '$_id.gameNameAutoGenerated',
          lineNum: { $first: '$lineNum' },
          countKills: { $sum: '$countKills' },
          countKillsByWorld: { $sum: '$countKillsByWorld' },
          countKillsByType: {
            $push: {
              type: '$_id.killModType',
              count: '$countKills',
            },
          },
        },
      },
      {
        $sort: { lineNum: 1 },
      },
    ]);
  }
}
