import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';

@Schema()
export class Log {
  @Prop({ required: true })
  logLineNum: number;
  @Prop({ required: true })
  eventType: string;
  @Prop({ required: false })
  eventValue: string;
  @Prop({ required: false })
  eventByPlayerName: string;
  @Prop({ required: false })
  eventByPlayerId: string;
  @Prop({ required: false })
  gameNameAutoGenerated: string;
  @Prop({ required: false })
  killerName: string;
  @Prop({ required: false })
  killedName: string;
  @Prop({ required: false })
  killModType: string;
}

export const LogSchema = SchemaFactory.createForClass(Log);
